### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by Demonsword27** [zixun/CrashEye#1]
老哥，为什么我clone到了本地，然后pod install 之后 ，进去之后也Convert了，什么都没做，为什么每个demo都运行不起来，我哪步出了问题
![unnamed](https://cloud.githubusercontent.com/assets/6824547/24240067/52fbf668-0feb-11e7-95ca-f5998965873f.jpg)

**Comment by Wbqqqq** [comment]
![Uploading 923935BA-4AF5-4D03-AF15-6C68900CE584.png…]()

**Comment by zixun** [comment]
@Wbqqqq 哥们 你的图好像挂了

**Comment by Demonsword27** [comment]
图传不上，，发你邮箱了。。。swift写的少，麻烦麻烦🙏。。

**Comment by zixun** [comment]
@Wbqqqq 已帮你更新图片。感谢反馈，后来api调整了，不需要调用open和close方法，添加监听delegate即可，remove掉会自动关闭。demo忘记更新api了

**Comment by zixun** [comment]
已更新

**Comment by Demonsword27** [comment]
好的老哥，稳   有问题再问你哈。
